FROM ghcr.io/graalvm/native-image-community:21 AS builder
WORKDIR /builder/

COPY pom.xml mvnw ./
COPY .mvn ./.mvn
COPY src ./src
RUN ./mvnw package -Pnative -DskipTests

FROM gcr.io/distroless/static-debian12:latest
WORKDIR /

COPY --from=builder /builder/target/fleetcoreserver-*-runner /application
USER quarkus
ENTRYPOINT ["/application", "-Dquarkus.http.host=0.0.0.0"]