name: Deploy OpenAPI to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build the target
        run: mvn install -Dspotless.check.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: target/openapi.json
          version: 5.x
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: swagger-ui

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4